name: Build and Test VSCode Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]  # Specify the Node.js version to use

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build the VSCode extension
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Package the extension
      run: |
        npm install -g vsce
        vsce package

    - name: Upload VSIX package
      uses: actions/upload-artifact@v2
      with:
        name: salesforce-quickaccess
        path: *.vsix
